### ISSUE TITLE
set up coveralls

### ISSUE THREAD

**Issue by arschles** [paypal/cascade#25]
https://coveralls.io/docs

haven't read docs thoroughly, so not sure if we can do this. investigate

**Comment by taylorleese** [comment]
It looks like we need to move to scoverage to get coveralls support integrated because there is no support for the sbt jacoco plugin yet. https://github.com/sbt/jacoco4sbt/issues/33

**Comment by taylorleese** [comment]
Closing this. See https://github.com/paypal/cascade/pull/81.
