### ISSUE TITLE
test in AbstractResourceActorSpecs fails under JDK 8, Scala 2.10.4 + 2.11.4

### ISSUE THREAD

**Issue by devmage** [paypal/cascade#80]
When running the full test suite under JDK 8, the following test failure is observed in `AbstractResourceActorSpecs`:

```
[info]     x send an error if response object can't be serialized
[error]  'null'
[error]
[error]   is not equal to
[error]
[error]  'HttpResponse(500 Internal Server Error,HttpEntity(application/json; charset=UTF-8,"Could not write response to json"),List(),HTTP/1.1)' (AbstractResourceActorSpecs.scala:37)
[info]
[error] Expected: HttpResponse(500 Internal Server Error,HttpEntity(application/json; charset=UTF-8,"Could not write response to json"),List(),HTTP/1.1)
[info]
[error] Actual:   null
```

**Comment by 2rs2ts** [comment]
The error you see here is because `probe.receiveOne` is not getting a message within the expected timeframe. Why does that happen? Search me, but that's the error.

**Comment by arschles** [comment]
@devmage please add jdk8 tests to the travis build matrix so we can consistently repro this on CI. link that PR to this issue

**Comment by devmage** [comment]
@arschles added, please see https://github.com/paypal/cascade/pull/84

**Comment by arschles** [comment]
thanks @devmage

**Comment by devmage** [comment]
So that's curious. Per Travis, the test failure is specifically an issue under JDK 8 *and* Scala 2.10.4. I've amended the issue title to reflect this.

**Comment by arschles** [comment]
k

**Comment by 2rs2ts** [comment]
@devmage Curious indeed. I'm pretty sure it happens on 2.11.4 too.

**Comment by devmage** [comment]
Well, luckily, we can test that. I'll add 2.11.4 as a build target for now, and we can remove it before merging.

**Comment by devmage** [comment]
@2rs2ts just as you said, it fails on 2.11.4 + JDK 8, but passes on 2.11.5 + JDK 8. Go figure.

**Comment by 2rs2ts** [comment]
Sounds like a scala bug. I have looked at this problem several times and never came to a conclusion on how we can guard against it. I am going to take one more look at this today but if I can't come up with anything my opinion is to not fix this as it's kinda not our responsibility and it's difficult if not impossible to guard against scala bugs.

**Comment by 2rs2ts** [comment]
So I can't track down why this is happening but it actually has something to do with the fact that that particular test tries to serialize the `testActor`. The `Try` wrapping `mapper.writeValueAsString` is not catching some fatal error. In IntelliJ sometimes I see something that implies a `StackOverflowError` which is a `VirtualMachineError` which is considered fatal by `Try` and won't be caught, but it's getting wrapped in a `JsonMappingException` by Jackson, so it shouldn't be blowing up the `Try`. But I can't reproduce this in the console.

The easy fix is to change the test to use something else that doesn't have a serializer but won't cause this problem.

**Comment by 2rs2ts** [comment]
You can see the gist of the problem if you just `println(testActor.toJson)`.

```
Failure(com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: akka.actor.LocalActorRefProvider["deadLetters"]->akka.actor.DeadLetterActorRef["provider"]->akka.actor.LocalActorRefProvider["deadLetters"]-> et cetera et cetera
```
