### ISSUE TITLE
JsonUtil's ObjectMapper should be configurable

### ISSUE THREAD

**Issue by 2rs2ts** [paypal/cascade#90]
Developers using cascade may want to change some of the `ObjectMapper`'s properties. I realize that you can just instantiate your own mapper and mix in the experimental scala features and configure it yourself, but for small changes, that's a lot of extra boilerplate and unnecessarily wasted RAM.

**Comment by taylorleese** [comment]
+1

**Comment by 2rs2ts** [comment]
In order to make this configurable at runtime we'd have to make sure that we don't expose the reference to the mapper lest users introduce race conditions, and we'd have to wrap it in an agent or an `AtomicReference` or something, which is too much overhead for a portion of our codebase which needs to be performant.

The best way to do this would be to enable users to specify the modifications at compile time, but it's impossible since `JsonUtil` is a singleton. To take out the singleton pattern we'd also have to have `HttpUtil` not be a singleton, and start passing instances of these things into the resource actors... very messy, and it screams dependency injection, but we took the cake pattern out of this project.

I'm putting a pin in this one.
