### ISSUE TITLE
Request timeouts are easily disrespected by actor inheritance for HttpResourceActors

### ISSUE THREAD

**Issue by 2rs2ts** [paypal/cascade#92]
The request timeout laid out for the `HttpResourceActor` can be easily circumvented by any services that an `AbstractResourceActor` talks to sending errant or delayed messages.

Say resource X talks to services A, B, and C via tells and it expects responses from all three in its `resourceReceive` method. A and B respond after 1 second but C responds after 4.5, which is greater than the `processRecvTimeout` in a `ResourceContext`, so the request *should* time out... but because it was only 3.5 seconds in between A/B's responses and C's, the actor does not get a `ReceiveTimeout` and the request times out after the 4 seconds, which is wrong.

Perhaps instead of using this timeout, we should be [scheduling](http://doc.akka.io/docs/akka/snapshot/scala/scheduler.html) a timeout message.

Thanks to @milesoc for helping me discover this issue.

**Comment by kionka** [comment]
A two actor system might be easier than trying to use the Akka Scheduler.

**Comment by devmage** [comment]
I like the idea of scheduling a timeout message. It allows for minimal change in other flows using cascade, and can be directly wired in to each request actor.

**Comment by 2rs2ts** [comment]
After looking into this more I'm perplexed as to why we don't just use [`spray`'s timeout handling](http://spray.io/documentation/1.1-SNAPSHOT/spray-routing/key-concepts/timeout-handling/).
